export * from './client-already-exists.error'
export * from './creation-date-future.error'
export * from './empy-name.error'
export * from './empy-phone.error'
export * from './id-alread-defined.error'
export * from './last-visit-before-creation.error'
export * from './last-visit-future.error'
export * from './negative-points.error'
