export * from './client-already-exists.error'
export * from './empy-phone.error'
export * from './last-visit-before-creation.error'
export * from './last-visit-future.error'
export * from './negative-points.error'
export * from './creation-in-future.error'
